# Generated by Django 5.0 on 2024-11-05 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentorg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='College',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studentorg.college'),
        ),
    ]
